version: '3'

volumes:
  postgres:
    driver: local


services:

  postgres:
    image: postgres:15.1-alpine
    container_name: hw4-postgres
    env_file:
      - .env
    ports:
      - '5431:5432'
    volumes:
      - database:/var/lib/postgresql/data
