spring:

  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5431/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true

security:
  jwt:
    secret: ${JWT_SECRET}
    access: ${JWT_ACCESS}
    refresh: ${JWT_REFRESH}

